### ISSUE TITLE
after installing nvidia-smi stops working

### ISSUE THREAD

**Issue by avnerbarr** [Syllo/nvtop#125]
I installed per instructions;
apt install nvtop

tried to run:
```
~$ nvtop
Impossible to initialize nvidia nvml : Driver/library version mismatch
```
now drivers are broken:
```
nvidia-smi
Failed to initialize NVML: Driver/library version mismatch
```

How do I fix this????

**Comment by Syllo** [comment]
If you are using Ubuntu, it is likely that another version of the driver got installed at the same time due to a dependency that only exists there.
Don't use the package on Ubuntu, use the manual install instead.

The easiest way to fix that is reboot your computer to load the right driver again.
The complex way is to use ``modprobe`` to unload the current driver and load the new one.

**Comment by NickLucche** [comment]
Same problem here, I solved with a hammer approach by uninstalling previous nvidia drivers `sudo apt purge "nvidia*"` and then selecting the desidered driver in Software&Updates->Additional Drivers

**Comment by metra4ok** [comment]
@Syllo 
> If you are using Ubuntu, it is likely that another version of the driver got installed at the same time due to a dependency that only exists there. Don't use the package on Ubuntu, use the manual install instead.

I guess it is a good idea to mention this issue in README to prevent new users from the same headache with re-loading nvidia drivers.

**Comment by Syllo** [comment]
Please follow the manual installation for Ubuntu if you are on anything < Ubuntu 22.04.
They have an extra dependency to the Nvidia driver that is not present on other distributions (e.g. Debian).
Similar to https://github.com/Syllo/nvtop/issues/51
