### ISSUE TITLE
AMDGPU power usage no longer shows up in kernel 6.6

### ISSUE THREAD

**Issue by emansom** [Syllo/nvtop#244]
When running `nvtop` on kernel version `6.6.0-rc3` the power usage no longer shows up.

**GPU**: AMD Radeon RX 550
**nvtop version**: 3.0.2

![Schermafdruk van 2023-10-02 16-50-10](https://github.com/Syllo/nvtop/assets/981494/1553fd30-ddc2-4861-916e-5a1d914b6020)

**Comment by emansom** [comment]
If you are wondering why the clocks are so low: i'm running with a tuned AMD PowerPlay profile optimized for power efficiency.

**Comment by Umio-Yasuno** [comment]
`nvtop` gets AMD GPU power consumption with `_amdgpu_query_sensor_info(gpu_info->amdgpu_device, AMDGPU_INFO_SENSOR_GPU_AVG_POWER, sizeof(out32), &out32)`.
https://github.com/Syllo/nvtop/blob/master/src/extract_gpuinfo_amdgpu.c#L727-L732

The AMDGPU driver now uses `AMDGPU_PP_SENSOR_GPU_AVG_POWER` internally due to recent changes.  
This causes some AMD GPUs that do not support `AMDGPU_PP_SENSOR_GPU_AVG_POWER` to return an error for `AMDGPU_INFO_SENSOR_GPU_AVG_POWER`.
https://gitlab.freedesktop.org/agd5f/linux/-/commit/47f1724db4fe0085b33cafd68bb8b7267678bb95

I will report it to [drm/amd](https://gitlab.freedesktop.org/drm/amd/-/issues) .

**Comment by Umio-Yasuno** [comment]
Reported: https://gitlab.freedesktop.org/drm/amd/-/issues/2897

**Comment by emansom** [comment]
@Umio-Yasuno Tested. Apologies for taking so long, forgot all about it.

https://gitlab.freedesktop.org/drm/amd/-/issues/2897#note_2163069

**Comment by emansom** [comment]
Patches have been merged in 6.7.2, this issue is now resolved for me. Tested on a AMD Radeon Polaris RX 580.
